Mvc/Models/Flight/CreateFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ARQ.Maqueta.Presentation.Mvc.Models;

namespace ARQ.Maqueta.Presentation.Mvc.ViewModels
{
    public class CreateFlightViewModel :  FlightViewModel
    {
    }
}

Mvc/Models/Flight/DetailsFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ARQ.Maqueta.Presentation.Mvc.ViewModels
{
    public class DetailsFlightViewModel : FlightViewModel
    {
    }
}

Mvc/Models/Flight/EditFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ARQ.Maqueta.Presentation.Mvc.ViewModels
{
    public class EditFlightViewModel : FlightViewModel
    {
    }
}

Mvc/Models/Flight/FlightViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using ARQ.Maqueta.Entities;
using Resources;

namespace ARQ.Maqueta.Presentation.Mvc.ViewModels
{
    public class FlightViewModel
    {
        [Display(Name = "Id", ResourceType = typeof(FlightResource))]
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(Shared), ErrorMessageResourceName = "RequiredField")]
        [StringLength(255)]
        [Display(Name = "Airline", ResourceType = typeof(FlightResource))]
        public string Airline { get; set; }

        [Required(ErrorMessageResourceType = typeof(Shared), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "SourceAirportID", ResourceType = typeof(FlightResource))]
        public string SourceAirportID { get; set; }

        [Display(Name = "SourceAirportName", ResourceType = typeof(FlightResource))]
        public string SourceAirportName { get; set; }

        [Required(ErrorMessageResourceType = typeof(Shared), ErrorMessageResourceName = "RequiredField")]
        [Display(Name = "DestinationAirportID", ResourceType = typeof(FlightResource))]
        public string DestinationAirportID { get; set; }

        [Display(Name = "DestinationAirportName", ResourceType = typeof(FlightResource))]
        public string DestinationAirportName { get; set; }

        [DisplayFormat(DataFormatString = "{0:n0}")]
        [Display(Name = "FuelNeeded", ResourceType = typeof(FlightResource))]
        public decimal FuelNeeded { get; set; }

        [Display(Name = "Stops", ResourceType = typeof(FlightResource))]
        public int Stops { get; set; }

        [DisplayFormat(DataFormatString = "{0:n0}")]
        [Display(Name = "Distance", ResourceType = typeof(FlightResource))]
        public decimal Distance { get; set; }

        [Display(Name = "Active", ResourceType = typeof(FlightResource))]
        public bool Active { get; set; }

        [Display(Name = "LastModifiedUser", ResourceType = typeof(FlightResource))]
        public string LastModifiedUser { get; set; }

        [Display(Name = "LastModifiedDate", ResourceType = typeof(FlightResource))]
        public DateTime LastModifiedDate { get; set; }

        public string Description
        {
            get
            {
                return SourceAirportName + " > " + DestinationAirportName;
            }
        }

        public IEnumerable<AiportViewModel> AiportList { get; set; }
    }
}

Mvc/Models/Flight/IndexFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ARQ.Maqueta.Presentation.Mvc.ViewModels
{
    public class IndexFlightViewModel : FlightViewModel
    {
        public FilterViewModel Filter { get; set; }
    }
}

Mvc/Controllers/ErrorPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ARQ.Maqueta.Presentation.Mvc.Extensions.Controllers;
using ARQ.Maqueta.Presentation.Mvc.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace ARQ.Maqueta.Presentation.Mvc.Controllers
{
    public class ErrorPageController : BaseController
    {
        public ActionResult Error()
        {
                return View();  
        }

        public ActionResult Unauthorized()
        {
            AuthenticationManager.SignOut();

            return View("~/Views/Shared/Unauthorized.cshtml");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

    }
}

Mvc/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ARQ.Maqueta.Presentation.Mvc.ApiCall;
using ARQ.Maqueta.Presentation.Mvc.ViewModels;
using ARQ.Maqueta.Entities.Entities;
using ARQ.Maqueta.Presentation.Mvc.Models.Shared;
using System.Threading.Tasks;
using ARQ.Maqueta.Entities;
using AutoMapper;
using ARQ.Maqueta.Presentation.Mvc.Extensions.Helpers;

namespace ARQ.Maqueta.Presentation.Mvc.Controllers
{
    public class FlightController : Controller
    {
        #region Members

        private FlightApiService flightService;
        private IEnumerable<AiportViewModel> aiportList;

        #endregion

        #region Constructors

        public FlightController()
        {
            this.flightService = new FlightApiService();
            this.aiportList = FileHelper.GetAiportsListItemsFromJsonFile();
        }

        #endregion

        // GET: Flight
        public ActionResult Index()
        {
            IndexFlightViewModel viewModel = new IndexFlightViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Filter(IndexFlightViewModel model, string returnUrl)
        {
            //Get value filter when push over buton Search
            Session["FlightSearchFilter"] = model.Filter.Flight;

            ViewBag.Filtro = true;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public virtual async Task<ActionResult> Load(GridRequestViewModel gridRequest)
        {
            //Initial load data
            var filter = Session["FlightSearchFilter"] != null ? (string)Session["FlightSearchFilter"] : string.Empty;
            var count = 0;

            Filtro filtro = new Filtro { Flight = filter };

            var flightList = await flightService.GetFlights(filtro.Flight);

            var displayRecords = flightList.Count;
            var totalRecords = 10;

            //var dateFormat = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "en" ? "MM/dd/yyyy" : "dd/MM/yyyy";
            //System.Globalization.DateTimeFormatInfo dtfi = System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat;
            //dtfi.DateSeparator = "/";

            //Create JSON value for pass the view
            return Json(new
            {
                iTotalDisplayRecords = displayRecords,
                iTotalRecords = totalRecords,
                sEcho = gridRequest.GridCustomData,
                aaData = flightList.Select(d => new { d.Id, d.Airline,
                    d.SourceAirportID,
                    d.SourceAirportName,
                    d.DestinationAirportID,
                    d.DestinationAirportName,
                    d.Distance,
                    d.FuelNeeded,
                    d.Stops,
                    d.Active })
            });
        }

        public async Task<ActionResult> Details(int id)
        {
            var flight = await this.flightService.GetFlight(id);

            var viewModel = Mapper.Map<Flight, DetailsFlightViewModel>(flight);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            Flight flight = new Flight();
            var viewModel = Mapper.Map<Flight, CreateFlightViewModel>(flight);

            ViewBag.AiportList = this.aiportList;

            ViewBag.IsNew = true;

            return View(viewModel);
        }

        [HttpPost]
        public async virtual Task<ActionResult> Create(CreateFlightViewModel flightModel)
        {
            if (ModelState.IsValid)
            {
                Flight flight = new Flight();

                var sourceAiport = this.aiportList.FirstOrDefault(x => x.Code == flightModel.SourceAirportID);
                var destinationAiport =this. aiportList.FirstOrDefault(x => x.Code == flightModel.DestinationAirportID);

                Mapper.Map<CreateFlightViewModel, Flight>(flightModel, flight);
                Mapper.Map<AiportViewModel, Aiport>(sourceAiport, flight.Source);
                Mapper.Map<AiportViewModel, Aiport>(destinationAiport, flight.Destination);

                flight.LastModifiedUser = User.Identity.Name;
                flight.LastModifiedDate = DateTime.Now;

                flight.Id = await flightService.PostFlight(flight);

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.IsNew = true;
                ViewBag.AiportList = this.aiportList;

                return View(flightModel);
            }
        }

        public async virtual Task<ActionResult> Edit(int id)
        {
            var flight = await this.flightService.GetFlight(id);
            var viewModel = Mapper.Map<Flight, EditFlightViewModel>(flight);

            ViewBag.AiportList = this.aiportList;

            ViewBag.IsNew = false;

            return View(viewModel);
        }

        [HttpPost]
        public async virtual Task<ActionResult> Edit(EditFlightViewModel flightModel)
        {
            if (ModelState.IsValid)
            {
                var flight = await this.flightService.GetFlight(flightModel.Id);
                var sourceAiport = this.aiportList.FirstOrDefault(x => x.Code == flightModel.SourceAirportID);
                var destinationAiport = this.aiportList.FirstOrDefault(x => x.Code == flightModel.DestinationAirportID);

                Mapper.Map<EditFlightViewModel, Flight>(flightModel, flight);
                Mapper.Map<AiportViewModel, Aiport>(sourceAiport, flight.Source);
                Mapper.Map<AiportViewModel, Aiport>(destinationAiport, flight.Destination);

                flight.LastModifiedUser = User.Identity.Name;
                flight.LastModifiedDate = DateTime.Now;

                await flightService.PutFlight(flight);

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.AiportList = this.aiportList;

                return View(flightModel);
            }
        }

        [HttpPost]
        public async virtual Task<ActionResult> Delete(int id)
        {
            try
            {
                await flightService.DeleteFlight(id);

            }
            catch (Exception ex)
            {

                Response.StatusCode = 500;
                return Content(ex.Message);
            }
            return Content(string.Empty);
        }
    }
}

Mvc/Views/Flight/Create.cshtml
@model CreateFlightViewModel

@{
    ViewBag.Title = Resources.Shared.AppName + " - " + string.Format(Resources.Shared.CreateViewTitle, "Flight");
}

<h2>@string.Format(Resources.Shared.CreateViewTitle, Resources.FlightResource.Flight)</h2>

<div class="form-commands-container">
    <button class="btn btn-default btn-sm back-button" title="@Resources.Shared.Back"><span class="glyphicon glyphicon-arrow-left"></span>@Resources.Shared.Back</button>
    <button class="btn btn-default btn-sm save-button" title="@Resources.Shared.Save"><span class="glyphicon glyphicon-ok"></span>@Resources.Shared.Save</button>
</div>

<div class="entity-form-container">
    @using (Html.BeginForm("Create", "Flight", FormMethod.Post, new { id = "FlightForm", enctype = "multipart/form-data", role = "form", @class = "form-horizontal" }))
    {
        @Html.ValidationSummary(true)
        @Html.Partial("_FlightEditor", Model)
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function() {
            formUtils.setupFormControls("FlightForm");
			formUtils.setupFormActionButtons({
                formId: "FlightForm",
                indexPageUrl: "@Url.Action("Index")",
                buttonsContainerSelector: ".form-commands-container"
			});

        });

    </script>
}

Mvc/Views/Flight/Details.cshtml
@model DetailsFlightViewModel
@{
    ViewBag.Title = Resources.Shared.AppName + " - " + string.Format(Resources.Shared.DetailsViewTitle, Model.Description);
}
<h2>@string.Format(Resources.Shared.DetailsViewTitle, Model.Description)</h2>

<div class="row">
    <div class="col-xs-12 form-commands-container">
        <button class="btn btn-default btn-sm back-button" title="@Resources.Shared.Back"><span class="glyphicon glyphicon-arrow-left"></span>@Resources.Shared.Back</button>
    </div>
</div>

<fieldset class="form-horizontal">
    <legend>@Resources.FlightResource.Flight</legend>
    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.Airline, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.Airline</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.SourceAirportID, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.SourceAirportID</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.SourceAirportName, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.SourceAirportName</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.DestinationAirportID, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.DestinationAirportID</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.DestinationAirportName, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.DestinationAirportName</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.FuelNeeded, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Html.DisplayFor(model => model.FuelNeeded) (L)</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.Stops, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Model.Stops</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.Distance, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@Html.DisplayFor(model => model.Distance) (KM)</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-field-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-sm-3 col-lg-4" })
            <div class="editor col-sm-7 col-lg-8">
                <p class="form-control-static">@(Model.Active ? "Yes" : "No")</p>
            </div>
        </div>
    </div>

</fieldset>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            formUtils.setupFormActionButtons({
                formId: "UsuarioForm",
                indexPageUrl: "@Url.Action("Index")",
                buttonsContainerSelector: ".form-commands-container"
            });
        });
    </script>
}

Mvc/Views/Flight/Edit.cshtml
@model EditFlightViewModel

@{
    ViewBag.Title = Resources.Shared.AppName + " - " + string.Format(Resources.Shared.EditViewTitle, Model.Description);
}

<h2>@string.Format(Resources.Shared.EditViewTitle, Model.Description)</h2>

<div class="form-commands-container">
    <button class="btn btn-default btn-sm back-button" title="@Resources.Shared.Back"><span class="glyphicon glyphicon-arrow-left"></span>@Resources.Shared.Back</button>
    <button class="btn  btn-default btn-sm save-button" title="@Resources.Shared.Save"><span class="glyphicon glyphicon-ok"></span>@Resources.Shared.Save</button>
</div>

<div class="entity-form-container">
    @using (Html.BeginForm("Edit", "Flight", FormMethod.Post, new { id = "FlightForm", enctype = "multipart/form-data", role = "form", @class = "form-horizontal" }))
    {
        @Html.ValidationSummary(true)
        @Html.Partial("_FlightEditor", Model)
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            formUtils.setupFormControls("FlightForm");
            formUtils.setupFormActionButtons({
                formId: "FlightForm",
                indexPageUrl: "@Url.Action("Index")",
                buttonsContainerSelector: ".form-commands-container"
            });
        });
    </script>
}

Mvc/Views/Flight/Index.cshtml
@model IndexFlightViewModel
@{
    ViewBag.Title = Resources.Shared.AppName + " - " + string.Format(Resources.Shared.IndexViewTitle, "Flight");
}

<h2>@string.Format(Resources.Shared.IndexViewTitle, Resources.FlightResource.Flight)</h2>

<div class="row">
    <section style="margin:17px;  text-align: left;;">
        <legend>@Resources.Shared.Filtro</legend>
        @using (Html.BeginForm("Filter", "Flight", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="row">
                <div class="form-field-group">
                    @Html.LabelFor(model => model.Filter.Flight, new { @class = "control-label col-sm-1 col-lg-1" })
                    <div class="editor col-sm-3 col-lg-3">
                        @Html.EditorFor(model => model.Filter.Flight)
                        @Html.ValidationMessageFor(model => model.Filter.Flight)
                    </div>
                </div>
            </div>


            <div>
                <div class="btn-group" style="float:right">

                    <button type="submit" id="search-filter" class="btn btn-default btn-sm btn-default " title="@(Resources.Shared.DoSearch)"><span class="glyphicon glyphicon-search"></span></button>
                    <button type="submit" id="clean-filter" class="btn btn-default btn-sm  " title="@(Resources.Shared.Clean)"><span class="glyphicon glyphicon-remove"></span></button>
                </div>
            </div>
        }

    </section>
</div>

<div class="row">
    <div class="grid-commands-container grid-top-buttons col-xs-5">
    </div>
</div>
<table id="FlightGrid" class="table table-striped table-bordered" width="100%"></table>
<div class="grid-commands-container grid-bottom-buttons ">
    @ToolbarButtons()
</div>

@helper ToolbarButtons()
{
    <button class="btn btn-default btn-sm create-button search-box" title="@Resources.Shared.Create"><span class="glyphicon glyphicon-plus-sign"></span>@Resources.Shared.Create</button>
}

@section scripts
{
    <script type="text/javascript">

        var oTable;
        var url = "@Url.Action("Load")";
        $(function () {

            var gridId = "FlightGrid";

            gridUtils.setupGridToolbarButtons({
                gridId: gridId,
                toolbarContainerSelector: ".grid-bottom-buttons, .grid-top-buttons",
                addUrl: "@Url.Action("Create")",
                reportUrl: "@Url.Action("Report")"
            });
            gridUtils.setupGridSearchBox({
                gridId: gridId,
                searchContainerSelector: ".grid-view-search"
            });
            gridUtils.setupGridRowButtons({ gridId: gridId });

            $("#search-filter").click(function () {
                //Save the filter values to read before
                var flight = $("#Filter_Flight").val();
                window.sessionStorage.setItem("FlightFiltro", flight);
            })

            if ('@ViewBag.Filtro' === 'True') {
                cargarDatos(gridId, url);
            }

            $.fn.dataTable.ext.errMode = 'throw';

            oTable = $("#" + gridId).dataTable({
                "aoColumns": [
                    { mData: "Id", sName: "Id", bVisible: false, bSortable: false },
                    {
                        sClass: "row-options",
                        bSortable: false,
                        mData: null,
                        sWidth: "5%",
                        mRender: function (data, type, datasource) {
                            var rowId = datasource.Id;
                            var editHtml = '<a href="@Url.Action("Edit")?id=' + rowId + '" class="row-edit btn btn-md" title="@Resources.Shared.Edit"><span class="glyphicon glyphicon-pencil" /></a>';
                            var detailsHtml = '<a href="@Url.Action("Details")?id=' + rowId + '" class="row-details btn btn-md" title="@Resources.Shared.Details"><span class="glyphicon glyphicon-eye-open" /></a>';
                            var deleteHtml = '<a href="@Url.Action("Delete")?id=' + rowId + '" class="row-delete btn btn-md" title="@Resources.Shared.Delete"><span class="glyphicon glyphicon-remove" /></a>';
                            return editHtml + detailsHtml + deleteHtml;
                        }
                    },

                        { mData: "Airline", sWidth: "20%", sName: "Airline", sTitle: "@Resources.FlightResource.Airline" },
                        { mData: "SourceAirportID", sWidth: "5%", sName: "SourceAirportID", sTitle: "@Resources.FlightResource.SourceAirportID" },
                        { mData: "SourceAirportName", sWidth: "30%", sName: "SourceAirportName", sTitle: "@Resources.FlightResource.SourceAirportName" },
                        { mData: "DestinationAirportID", sWidth: "5%", sName: "DestinationAirportID", sTitle: "@Resources.FlightResource.DestinationAirportID" },
                        { mData: "DestinationAirportName", sWidth: "30%", sName: "DestinationAirportName", sTitle: "@Resources.FlightResource.DestinationAirportName" },
                        @*{ mData: "FuelNeeded", sName: "FuelNeeded", sTitle: "@Resources.FlightResource.FuelNeeded" },
                        { mData: "Stops", sName: "Stops", sTitle: "@Resources.FlightResource.Stops" },
                        { mData: "Distance", sName: "Distance", sTitle: "@Resources.FlightResource.Distance" },*@
                        { mData: "Active", sName: "Active", sTitle: "@Resources.FlightResource.Active", mRender: function (data, type, datasource) { return "<span class='boolean-" + data + "' />"; } },

                ],
               
                "aaSorting": [[2, "asc"]],
                "sPaginationType": "full_numbers",
                "oLanguage": datatables_locale,
                "bProcessing": true,
                "bFilter": true,
                "bServerSide": true,
                "sAjaxSource": url,
                "sServerMethod": "POST",
                "sDom": 'rtip<"pull-left"l>',
                "bStateSave": true,
                "sCookiePrefix": "radarc",
                "fnCookieCallback": function (sName, oData, sExpires, sPath) {
                    return sName + "=" + JSON.stringify(oData) + ";path=" + sPath;
                },
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": url,
                        "data": aoData,
                        "success": fnCallback,
                        "error": function (jqXHR, textStatus, errorThrown) {
                            InformarError(jqXHR, textStatus, errorThrown);
                        }
                    });
                },
                "fnStateLoaded": function (oSettings) {
                    var search = oSettings.oPreviousSearch;
                    if (search) {
                        $("input.search-box").val(search.sSearch);

                        var nombre = window.sessionStorage.getItem("FlightFiltro");
                        $("#Filter_Flight").val(nombre);

                        RemoveStorage();
                    }
                }
            });

        });

        function RemoveStorage() {
            window.sessionStorage.removeItem("FlightFiltro");
        }

        function InformarError(jqXHR, textStatus, errorThrown) {
            @if (Request.IsAuthenticated)
            {
                // Unauthorized error
            <text>
            window.location.href = "@Url.Action("Unauthorized", "ErrorPage")";
            </text>
            }
            else {
                // Internal server error (500), NotFound
            <text>
            window.location.href = "@Url.Action("Error", "ErrorPage")";
            </text>
            }
        }

        function cargarDatos(gridId, url) {
            alert('Testing');
            oTable = $("#" + gridId).dataTable({
                "aoColumns": [
                    { mData: "Id", sName: "Id", bVisible: false, bSortable: false },
                    {
                        sClass: "row-options",
                        bSortable: false,
                        mData: null,
                        mRender: function (data, type, datasource) {
                            var rowId = datasource.Id;
                            var editHtml = '<a href="@Url.Action("Edit")?id=' + rowId + '" class="row-edit btn btn-md" title="@Resources.Shared.Edit"><span class="glyphicon glyphicon-pencil" /></a>';
                            var detailsHtml = '<a href="@Url.Action("Details")?id=' + rowId + '" class="row-details btn btn-md" title="@Resources.Shared.Details"><span class="glyphicon glyphicon-eye-open" /></a>';
                            var deleteHtml = '<a href="@Url.Action("Delete")?id=' + rowId + '" class="row-delete btn btn-md" title="@Resources.Shared.Delete"><span class="glyphicon glyphicon-remove" /></a>';
                            return editHtml + detailsHtml + deleteHtml;
                        }
                    },

                        { mData: "Airline", sName: "Airline", sTitle: "@Resources.FlightResource.Airline" },
                        { mData: "SourceAirportID", sName: "SourceAirportID", sTitle: "@Resources.FlightResource.SourceAirportID" },
                        { mData: "SourceAirportName", sName: "SourceAirportName", sTitle: "@Resources.FlightResource.SourceAirportName" },
                        { mData: "DestinationAirportID", sName: "DestinationAirportID", sTitle: "@Resources.FlightResource.DestinationAirportID" },
                        { mData: "DestinationAirportName", sName: "DestinationAirportName", sTitle: "@Resources.FlightResource.DestinationAirportName" },
                        { mData: "FuelNeeded", sName: "FuelNeeded", sTitle: "@Resources.FlightResource.FuelNeeded" },
                        { mData: "Stops", sName: "Stops", sTitle: "@Resources.FlightResource.Stops" },
                        { mData: "Distance", sName: "Distance", sTitle: "@Resources.FlightResource.Distance" },
                        { mData: "Active", sName: "Active", sTitle: "@Resources.FlightResource.Active", mRender: function (data, type, datasource) { return "<span class='boolean-" + data + "' />"; } },

                ],
                "aaSorting": [[2, "asc"]],
                "sPaginationType": "full_numbers",
                "oLanguage": datatables_locale,
                "bRetrieve": true,
                "bProcessing": true,
                "bFilter": true,
                "bServerSide": true,
                "sAjaxSource": url,
                "sServerMethod": "POST",
                "sDom": 'rtip<"pull-left"l>',
                "bStateSave": true,
                "sCookiePrefix": "radarc",
                "fnCookieCallback": function (sName, oData, sExpires, sPath) {
                    return sName + "=" + JSON.stringify(oData) + ";path=" + sPath;
                },
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": url,
                        "data": aoData,
                        "success": fnCallback
                    });
                },
                "fnStateLoaded": function (oSettings) {
                    var search = oSettings.oPreviousSearch;
                    if (search) {
                        $("input.search-box").val(search.sSearch);

                    }
                },
                "fnInitComplete": function (oSettings) {
                }

            });
        }

    </script>
}